### ISSUE TITLE
Is this app supposed to be published on google store?

### ISSUE THREAD

**Issue by erikng** [salopensource/chromesal#1]
It's not entirely obvious if this is an app that will be deployed from the google store or something we internally deploy ourselves.

I tried looking for `ChromeSal` and didn't find anything. Apologies if this project is still not finished yet and I am asking pre-mature questions.

**Comment by grahamgilbert** [comment]
You should deploy from the chrome store. Paste the ID into gsuite admin.

**Comment by erikng** [comment]
Where is the ID? I didn't see it in the readme.

**Comment by grahamgilbert** [comment]
Direct link is in the pdf of the slides where this project was publicly launched on my site.

**Comment by erikng** [comment]
For anyone else wanting to know:

graham.at/chromesal

Which then goes to: https://chrome.google.com/webstore/detail/chromesal/ohnahlfkoiaeknjhhcnhcjgpemccoklg
