### ISSUE TITLE
Can You Update Chrome Web Store to Version 2

### ISSUE THREAD

**Issue by nathandarnell** [salopensource/chromesal#4]
I'm deploying Sal v4 and can get my macs to check in but my Chromebooks won't.  Looking into it the Chrome extension in the web store is version 1.0.1.5 and not 2.0.0 like on GitHub.  

The error I'm getting is: `Uncaught InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.` This looks to be unused in v2 and appears to fix the problem.

**Comment by grahamgilbert** [comment]
You are correct. If you are deploying Sal 4, you probably want to vendor the extension yourself onto your company web store.

________________________________

**Comment by nathandarnell** [comment]
Thank you.  I deployed it for my Chromebooks and added to the readme in this PR: #5
